# Generated by Django 4.1.5 on 2023-01-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="img_url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
